/**
 * OpenAI 模型目录（2026年8月最新）
 */
import type { AIModel } from '@/types';

export const openaiModels: AIModel[] = [
  {
    id: 'gpt-5.6-sol',
    name: 'GPT-5.6 Sol',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 2026 年最新超级旗舰模型，105 万超长上下文，支持全模态输入、深度思考与复杂视频长篇解说创作。',
    features: ['最高智能', '多模态', '1.05M 上下文', '深度推理'],
    tokenLimit: 1050000,
    contextWindow: 1050000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.6-terra',
    name: 'GPT-5.6 Terra',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 2026 最新平衡旗舰，在极高智能水平与高性价比之间取得最佳平衡，适合专业脚本与影视分镜生成。',
    features: ['高性能', '多模态', '高性价比'],
    tokenLimit: 500000,
    contextWindow: 500000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.6-luna',
    name: 'GPT-5.6 Luna',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 2026 极速高吞吐模型，响应迅速、成本极低，适合批量视频解说文案批量生成与风格改写。',
    features: ['极速响应', '超低成本', '批量处理'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.5',
    name: 'GPT-5.5',
    provider: 'openai',
    category: ['text', 'code', 'image', 'video'],
    description: 'OpenAI 旗舰多模态模型，支持视频素材分析与解说文案生成。',
    features: ['多模态', '高智能', '视频理解'],
    tokenLimit: 256000,
    contextWindow: 256000,
    isPro: true,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
  {
    id: 'gpt-5.4-mini',
    name: 'GPT-5.4 Mini',
    provider: 'openai',
    category: ['text', 'code', 'image'],
    description: 'OpenAI 高性价比轻量模型。',
    features: ['高性价比', '快速响应', '多模态'],
    tokenLimit: 200000,
    contextWindow: 200000,
    isPro: false,
    pricing: { input: 0, output: 0, unit: 'see platform.openai.com' },
  },
];
